# Test goal: CUDA GPU communications with OpenMPI,NVSHMEM
# Test intents (should use as recent as possible dependencies):
#   OS: Ubuntu oldest supported
#   GPU: CUDA newest supported with its newest supported gcc
#   HW: dual NVIDIA GPU (CC 7.0 or newer required)
#   MPI: OpenMPI
#   Features: GPU direct communications (manual) + update (regression tests with dual GPU)
#   Scope: configure, build, regression tests
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 20.04
#   Build type: RelWithDebInfo
#   Compiler: GCC 11.1
#   GPU: CUDA 11.7.1
#   SIMD: SSE 4.1
#   FFT: FFTW3
#   Parallelism np/ntomp: 4/1 (regression tests with dual GPU)

gromacs:gcc-11-cuda-11.7.1:configureMPI-NVSHMEM:
  extends:
    - .gromacs:base:configure
    - .use-gcc:base
    - .use-cuda
    - .use-mpi
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-gcc-11-cuda-11.7.1
  variables:
    CMAKE: /usr/local/cmake-3.21.2/bin/cmake
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=SSE4.1"
    CMAKE_EXTRA_OPTIONS: "-DGMX_NVSHMEM=ON -DNVSHMEM_ROOT=/opt/nvidia/hpc_sdk/Linux_x86_64/2022/comm_libs/nvshmem"
    COMPILER_MAJOR_VERSION: 11

gromacs:gcc-11-cuda-11.7.1:buildMPI-NVSHMEM:
  extends:
    - .variables:default
    - .gromacs:base:build
    - .before_script:default
    - .use-ccache
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-gcc-11-cuda-11.7.1
  variables:
    CMAKE: /usr/local/cmake-3.21.2/bin/cmake
    CMAKE_EXTRA_OPTIONS: "-DGMX_NVSHMEM=ON -DNVSHMEM_ROOT=/opt/nvidia/hpc_sdk/Linux_x86_64/2022/comm_libs/nvshmem"
  needs:
    - job: gromacs:gcc-11-cuda-11.7.1:configureMPI-NVSHMEM

gromacs:gcc-11-cuda-11.7.1:testMPI-NVSHMEM:
  extends:
    - .gromacs:base:test
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-gcc-11-cuda-11.7.1
  variables:
    CMAKE: /usr/local/cmake-3.21.2/bin/cmake
    KUBERNETES_EXTENDED_RESOURCE_NAME: "nvidia.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 2
    GMX_ENABLE_DIRECT_GPU_COMM: 1
    # if NVSHMEM uses NCCL it requires more than 4 GB of GPU RAM as min memory,
    # in CI we've GPUs like T400 which have 4 GB RAM so we disable NVSHMEM's
    # NCCL usage, as NCCL isn't required in our NVSHMEM usage.
    NVSHMEM_DISABLE_NCCL: 1
    GMX_TEST_REQUIRED_NUMBER_OF_DEVICES: 2
    GMX_TEST_LABELS: "QuickGpuTest|SlowGpuTest"
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:gcc-11-cuda-11.7.1:buildMPI-NVSHMEM

gromacs:gcc-11-cuda-11.7.1:regressiontest-gpucommupd-MPI-NVSHMEM:
  # Test parallelism np/ntomp: 4/1
  # Test parallelism GPU: direct communications, update
  extends:
    - .gromacs:base:regressiontest
    - .rules:post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-gcc-11-cuda-11.7.1
  variables:
    CMAKE: /usr/local/cmake-3.21.2/bin/cmake
    KUBERNETES_EXTENDED_RESOURCE_NAME: "nvidia.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 2
    REGRESSIONTEST_PME_RANK_NUMBER: 0
    REGRESSIONTEST_TOTAL_RANK_NUMBER: 4
    REGRESSIONTEST_OMP_RANK_NUMBER: 1
    REGRESSIONTEST_PARALLEL: "-np"
    GMX_ENABLE_DIRECT_GPU_COMM: 1
    GMX_TEST_REQUIRED_NUMBER_OF_DEVICES: 2
    # if NVSHMEM uses NCCL it requires more than 4 GB of GPU RAM as min memory,
    # in CI we've GPUs like T400 which have 4 GB RAM so we disable NVSHMEM's
    # NCCL usage, as NCCL isn't required in our NVSHMEM usage.
    NVSHMEM_DISABLE_NCCL: 1
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:gcc-11-cuda-11.7.1:buildMPI-NVSHMEM
    - job: regressiontests:prepare
  artifacts:
    paths:
      - regressiontests
    when: always
    expire_in: 1 week

